name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4688f4c4ca2732a27755cb78caa3a59c11bcc5dab7b050a6f7e936dfc8b8c5a4"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
