name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdd929bec4f177a38ffa05e01d73c6e2e260b7d824e481fb8123099e00e2b06b"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
