name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e9b3b2bc988fbc1977af97e09fd139e11be838249e672bc92a5dd7d7cc22d20"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
