name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7843d028d910f6f5dd87b231fb3da2285605a685e48673edb3663e71b8ba3314"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
