name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "056dcf85ff4f7d69f89c1a3ad420515aa692144cd772f7786217ce283a6722c6"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
