name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17138380e0443191ff905808b4ad887458425bd80eeb443fb18027e76de78ce4"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
