name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b20923ae2672e95e547362410a63cb8908367fe4ed6818802c2f866ebee76452"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
