name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c6f99aa87107cbfe59677003cd27e6a8fc2cb7789a44e19b8c689a579cf25f1"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
