name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef2e3422abee33ab86388b3df2208d33358bdcf6478a1eacc6b46ea363fe64fc"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
