name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53d08f868d6d06f5318bc6d1549fe538eabdc92890fe739de2dccea449b6347f"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
