name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a797671fe66a5541b0becab13e152eb94d804d2d27a78054f99d4e1ac7340b2"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
